### ISSUE TITLE
No output from stderr

### ISSUE THREAD

**Issue by Histmy** [alpacamybags118/yt-dlp-exec#2]
Hello,

I don't know if I am missing some way to change it, but to me it seems like I can't get output from `stderr`. After looking at the code I found this line: https://github.com/alpacamybags118/yt-dlp-exec/blob/05c967f68df4c06bc3f2147f37c4035cd12a8446/src/index.js#L31 If I understand it correctly, it is only allowing `stdout` and ignoring `stdin` and `stderr`.

Is it intended like this? I need to be able to read `stderr`, because I would like to pipe output from `stdout` to ffmpeg and still be able to read progress of downloading from `stderr`.

**Comment by alpacamybags118** [comment]
Thanks for brining this up, yup that looks like its the case. What I think I'll do is make an update this weekend that lets you pass in your own configuration but defaults to only piping stdout if nothing is passed in. Should get to it tonight or tomorrow, so I'll link the PR here.

**Comment by alpacamybags118** [comment]
@Histmy PR is out, feel free to take a look. will merge tomorrow unless you have any concerns.

**Comment by Histmy** [comment]
Looks good to me. Thanks for fixing it. 👍

**Comment by alpacamybags118** [comment]
Release has been cut https://github.com/alpacamybags118/yt-dlp-exec/releases/tag/0.1.0 , thanks again for your feedback!
